# Site
name: "AAIEP"
title: "AAIEP"
description: "AAIEP, a tua voz na academia. Faz-te ouvir connosco."
logo: 'assets/images/logostd.png'     # nota, este é o logotipo usado no site, completamente a preto, não alterar
favicon: 'assets/images/logodarksimple.png'
baseurl: ''
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: geral@aaiep.pt
mandato: "2021/2022"

# Membros da AAIEP
# Não apagar de mandato para mandato, é necessário para os posts passados funcionarem
# Quando mudar de mandato, ou se alguém sai, alterar a variável "mandato" para FALSE.

# NOTA IMPORTANTE:
# Os primeiros 5 autores são a Direção, a Mesa, o Conselho Fiscal e a Comunicação e Imagem. Estes devem ter "mandato: FALSE"
# de modo a não entrar em conflito com outras partes do site. Se quiserem adicionar mais, como o "Cultural"
# por favor façam também com o "mandato: FALSE"

authors:
  anon:
    name: anonimo
    display_name: Anónimo
    avatar: 'assets/images/anon.png'
    description: "Publicações anónimas."
    mandato: FALSE

  mesa:
    name: mesa
    display_name: Mesa da Assembleia Geral
    avatar: 'assets/images/oficiallogo.jpg'
    email: mesa@aaiep.pt
    web: 'aga'
    description: "Mesa da Assembleia Geral de Alunos da AAIEP."
    mandato: FALSE
  direcao:
    name: direcao
    display_name: Direção
    avatar: 'assets/images/oficiallogo.jpg'
    email: direcao@aaiep.pt
    web: 'direcao'
    description: "Direção da AAIEP."
    mandato: FALSE
  fiscal:
    name: fiscal
    display_name: Conselho Fiscal
    avatar: 'assets/images/oficiallogo.jpg'
    email: fiscal@aaiep.pt
    web: 'fiscal'
    description: "Conselho Fiscal da AAIEP."
    mandato: FALSE
  eleitoral:
    name: eleitoral
    display_name: Comissão Eleitoral
    avatar: 'assets/images/oficiallogo.jpg'
    email: eleicoes@aaiep.pt
    web: 'eleicoes'
    description: "Comissão Eleitoral da AAIEP."
    mandato: FALSE
  ci:
    name: ci
    display_name: Comunicação
    avatar: 'assets/images/oficiallogo.jpg'
    description: "Departamento de Comunicação e Imagem."
    mandato: FALSE
  voluntariado:
    name: voluntariado
    display_name: Voluntariado
    avatar: 'assets/images/oficiallogo.jpg'
    web: 'voluntariado'
    description: "Bolsa de Voluntariado da AAIEP."
    mandato: FALSE
  cultural:
    name: cultural
    display_name: Cultural
    avatar: 'assets/images/oficiallogo.jpg'
    web: 'cultural'
    description: "Departamento Cultural da AAIEP."
    mandato: FALSE

# Direção
  matildepacheco:
    name: matildepacheco
    display_name: Matilde Pacheco
    avatar: 'assets/images/avatars/equipa21/matildepacheco.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Presidente da Direção."
    mandato: TRUE
  matildecampos:
    name: matildecampos
    display_name: Matilde Campos
    avatar: 'assets/images/avatars/equipa21/matildecampos.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vice-Presidente da Direção."
    mandato: TRUE
  rodrigoleitao:
    name: rodrigoleitao
    display_name: Rodrigo Leitão
    avatar: 'assets/images/avatars/equipa21/rodrigoleitao.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vice-Presidente da Direção."
    mandato: TRUE
  miguelinacio:
    name: miguelinacio
    display_name: Miguel Inácio
    avatar: 'assets/images/avatars/equipa21/miguelinacio.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Tesoureiro."
    mandato: TRUE
  catarinanabais:
    name: catarinanabais
    display_name: Catarina Nabais
    avatar: 'assets/images/avatars/equipa21/catarinanabais.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Secretária-Geral da Direção."
    mandato: TRUE

# Mesa
  cesarcaldeira:
    name: cesarcaldeira
    display_name: César Caldeira
    avatar: 'assets/images/avatars/equipa21/cesarcaldeira.jpg'
    email: mesa@aaiep.pt
    web: '/mesa'
    description: "Presidente da Mesa da AGA."
    mandato: TRUE
  cristianapinto:
    name: cristianapinto
    display_name: Cristiana Pinto
    avatar: 'assets/images/avatars/equipa21/cristianapinto.jpg'
    email: mesa@aaiep.pt
    web: aga
    description: "Vice-Presidente da Mesa da AGA."
    mandato: TRUE
  miguelcostal:
    name: miguelcostal
    display_name: Miguel Costal
    avatar: 'assets/images/avatars/equipa21/miguelcostal.jpg'
    email: mesa@aaiep.pt
    web: aga
    description: "Secretário da Mesa da AGA."
    mandato: TRUE

# Conselho Fiscal
  inessantareno:
    name: inessantareno
    display_name: Inês Santareno
    avatar: 'assets/images/avatars/equipa21/inessantareno.jpg'
    email: fiscal@aaiep.pt
    web: fiscal
    description: "Presidente do Conselho Fiscal."
    mandato: TRUE
  marianasetra:
    name: marianasetra
    display_name: Mariana Setra
    avatar: 'assets/images/avatars/equipa21/marianasetra.jpg'
    email: fiscal@aaiep.pt
    web: fiscal
    description: "Vice-Presidente do Conselho Fiscal."
    mandato: TRUE
  rafaelaguimaraes:
    name: rafaelaguimaraes
    display_name: Rafaela Guimarães
    avatar: 'assets/images/avatars/equipa21/rafaelaguimaraes.jpg'
    email: fiscal@aaiep.pt
    web: fiscal
    description: "Secretária do Conselho Fiscal."
    mandato: TRUE

# Vogais
  migueljustino:
    name: migueljustino
    display_name: Miguel Justino
    avatar: 'assets/images/avatars/equipa21/migueljustino.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Eventos."
    mandato: TRUE
  brunosilva:
    name: brunosilva
    display_name: Bruno Silva
    avatar: 'assets/images/avatars/equipa21/brunosilva.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Eventos."
    mandato: TRUE
  britneygoncalves:
    name: britneygoncalves
    display_name: Britney Gonçalves
    avatar: 'assets/images/avatars/equipa21/britneygoncalves.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Comunicação e Imagem."
    mandato: TRUE
  beatrizluis:
    name: beatrizluis
    display_name: Beatriz Luís
    avatar: 'assets/images/avatars/equipa21/beatrizluis.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Comunicação e Imagem."
    mandato: TRUE
  miguelfigueiredo:
    name: miguelfigueiredo
    display_name: Miguel Figueiredo
    avatar: 'assets/images/avatars/equipa21/miguelfigueiredo.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal da Cultura."
    mandato: TRUE
  danielcarrapato:
    name: danielcarrapato
    display_name: Daniel Carrapato
    avatar: 'assets/images/avatars/equipa21/danielcarrapato.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal da Cultura."
    mandato: TRUE
  patriciavaz:
    name: patriciavaz
    display_name: Patrícia Vaz
    avatar: 'assets/images/avatars/equipa21/patriciavaz.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal dos 2º e 3º Ciclos."
    mandato: TRUE
  margaridapaim:
    name: margaridapaim
    display_name: Margarida Paim
    avatar: 'assets/images/avatars/equipa21/margaridapaim.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Erasmus."
    mandato: TRUE
  isabellabaltazar:
    name: isabellabaltazar
    display_name: Isabella Baltazar
    avatar: 'assets/images/avatars/equipa21/isabellabaltazar.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Apoio ao Aluno."
    mandato: TRUE
  carolinaormonde:
    name: carolinaormonde
    display_name: Carolina Ormonde
    avatar: 'assets/images/avatars/equipa21/carolinaormonde.jpg'
    email: direcao@aaiep.pt
    web: direcao
    description: "Vogal de Responsabilidade Social."
    mandato: TRUE

###############################################################################
# !!! ATENÇÃO !!!
# Estão a entrar na zona proíbida de alterações
# YOU HAVE BEEN WARNED !
###############################################################################

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
