# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: AAIEP
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Bulma Theme
remote_theme: chrisrhymes/bulma-clean-theme

# --------- Config --------- #

lang: pt-PT
footer_menu: footer
logo: /assets/images/logo_fill_emblem_light.svg
paginate: 5
paginate_path: "/blog/page:num"
fixed_navbar: top
permalink: pretty

# ------ Collections ------- #

collections:
  institucional:
    path: /:collection/:path/
    output: true
  areas:
    path: /:collection/:path/
    output: true
  guia-site:
    path: /:collection/:path/
    output: true

# --------- Config --------- #

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "blog"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "AAIEP"
      layout: "post"
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
  -
    scope:
      path: ""
      type: "institucional"
    values:
      layout: "page"
      menubar: institucional_menu
  -
    scope:
      path: ""
      type: "areas"
    values:
      layout: "page"
      menubar: areas_menu
  -
    scope:
      path: ""
      type: "guia-site"
    values:
      layout: "page"
      menubar: guia_site_menu


